### ISSUE TITLE
Deprecation Warning for npx h2-compile

### ISSUE THREAD

**Issue by mnigh** [hydrogen-design-system/hydrogen.css#1]
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($i, $r)
More info and automated migrator: https://sass-lang.com/d/slash-div

`max-width: ($i / $r * 100%);`

resources/css/hydrogen/utilities/_utility-flex-grid.scss 54:21  h2-utility-flex-grid()

**Comment by JoshBeveridge** [comment]
This should be all fixed up in 1.1.0 #2 :)

Thanks @mnigh!
