### ISSUE TITLE
Read in files with path.resolve so npm workspaces can work

### ISSUE THREAD

**Issue by patcon** [hydrogen-design-system/hydrogen.css#72]
Hi! While trying to get npm workspaces working, I realized that hydrogen does some things that assume its going to find node_modules in the package root. E.g, it runs file read functions assuming it will find its own files in `./node_modules/<...>`, for example:

https://github.com/hydrogen-design-system/hydrogen.css/blob/d566c8a1acc911999a63c40901e57b8519390090/lib/scripts/functions/config-load.js#L11-L13

But with workspaces, this isn't necessarily the case. Workspaces will store the node_modules up a level if they're shared deps.

I'm not sure the original rationale, so perhaps it's more complicated, but I believe this can be resolved by using 
`path.resolve(__dirname)` more liberally within the codebase when node_modules is used rn: https://ultimatecourses.com/blog/relative-paths-with-node-readfilesync

(I worked through a few errors, and this seems to fix things, there was just a lot of search-replacing to do, and I wasn't sure if there were other reasons you were reading files that way :) )

**Comment by petertgiles** [comment]
🤯 This might be source of my hydrogen error when trying to run as root in a container!

**Comment by JoshBeveridge** [comment]
After taking a look, this should be relatively straightforward. I'll look at getting a PR up.

**Comment by JoshBeveridge** [comment]
`1.1.17` should resolve this :) Feel free to reopen if something crops up.

**Comment by patcon** [comment]
Thanks Josh!
