### ISSUE TITLE
CLI bins still not executable

### ISSUE THREAD

**Issue by patcon** [hydrogen-design-system/hydrogen.css#82]
Ran into some issues with npm run h2-build still not working, and did some troubleshooting

### Downloading package from npm

```
cd /tmp
wget $(npm view @hydrogen-design-system/hydrogen.css dist.tarball)
tar -xvzf hydrogen.css-1.1.17.tgz
ls -al package/bin
```
<img width="422" alt="Screen Shot 2022-02-08 at 2 50 36 AM" src="https://user-images.githubusercontent.com/305339/152941806-52d338b8-f59a-46f5-b6ba-b33fb5aa911c.png">

### Cloning repo from GitHub

```
cd /tmp
git clone hydrogen-design-system/hydrogen.css
ls -al hydrogen.css/bin
```
<img width="469" alt="Screen Shot 2022-02-04 at 4 29 41 PM" src="https://user-images.githubusercontent.com/305339/152941912-809c7d55-c10d-43ba-bc81-33e682599f06.png">

---

So it seems like the executable bits still aren't set properly in the compressed npm package itself. This might be an issue with the exec perm being incorrect locally on your laptop, and so the packaging process (run on your workstation) is generated package diff from git repo. I vaguely recall that pulling a commit with only permission changes might be buggy in git, depending on filesystem.

Might you be able to reclone and repackage (and confirm that executable bits are set correctly)? Thanks!

**Comment by patcon** [comment]
Sanity check: confirmed that +x is set for webpack-cli's binary pulled from npm repo

<img width="420" alt="Screen Shot 2022-02-18 at 1 17 20 PM" src="https://user-images.githubusercontent.com/305339/154739901-47fc840b-b4ed-4ac7-8a48-de4d55b03b86.png">

**Comment by JoshBeveridge** [comment]
@patcon @petertgiles Do y'all mind checking the `wget` tarball again for me now? I've since published `1.1.19` using Github Actions, so I want to see if this new set up respects the permission settings.

**Comment by patcon** [comment]
Yay! Resolved!

<img width="522" alt="Screen Shot 2022-02-20 at 5 10 34 PM" src="https://user-images.githubusercontent.com/305339/154866554-38574d3c-76f4-4c70-a6b9-4dcc818b78f4.png">

And now we _wait_...! hopefully that was the origin 🤞

**Comment by patcon** [comment]
What ended up being the resolution btw? Anything worth documenting, or anything to change to ensure that others don't have to figure this out again? 🙂

**Comment by JoshBeveridge** [comment]
The only difference was where the tarball was packaged - the package is set up to be published through Github using the release trigger moving forward, so this shouldn't be a problem given that they won't be published locally.
